export const EventType = {
    INVESTIGATION_STARTED: "investigation.started",
    INVESTIGATION_RECOVERED: "investigation.recovered",
    INVESTIGATION_STATE_CHANGED: "investigation.state_changed",
    INVESTIGATION_WOKEN: "investigation.woken",
    INVESTIGATION_HIBERNATED: "investigation.hibernated",
    INVESTIGATION_STOPPED: "investigation.stopped",
    INVESTIGATION_FAILED: "investigation.failed",
    HARNESS_PREFLIGHT_SUCCEEDED: "harness.preflight_succeeded",
    HARNESS_PREFLIGHT_FAILED: "harness.preflight_failed",
    ASSUMPTIONS_PROPOSED: "assumptions.proposed",
    ASSUMPTION_RESEARCH_STARTED: "assumption.research_started",
    ASSUMPTION_EXHAUSTED: "assumption.exhausted",
    ASSUMPTION_CONFIRMED: "assumption.confirmed",
    RUN_STARTED: "run.started",
    RUN_SUCCEEDED: "run.succeeded",
    RUN_FAILED: "run.failed",
    RUN_TIMED_OUT: "run.timed_out",
    RUN_CANCELLED: "run.cancelled",
    RUN_BLOCKED: "run.blocked",
    FINDING_CLAIMED: "finding.claimed",
    VERIFICATION_STARTED: "verification.started",
    FINDING_CONFIRMED: "finding.confirmed",
    FINDING_REFUTED: "finding.refuted",
    BREAKTHROUGH_RECORDED: "breakthrough.recorded",
    CAPABILITY_REQUESTED: "capability.requested",
    CAPABILITY_ANSWERED: "capability.answered",
    REPORT_GENERATED: "report.generated"
} as const;
export type EventType = (typeof EventType)[keyof typeof EventType];
